apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: yc-pool
  namespace: metallb-system
spec:
  addresses:
  - 51.250.10.227/32
  - 51.250.22.46/32
  - 51.250.32.66/32
  autoAssign: true
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2adv
  namespace: metallb-system
spec:
  ipAddressPools:
  - yc-pool
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: metallb
  namespace: metallb-system
data:
  config: |
    address-pools:
    - name: yc-pool
      protocol: layer2
      addresses:
      - 51.250.10.227/32
