name: Terraform Infrastructure
on:
  push:
    branches: [ "main" ]
    paths:
      - '02-infra/**'
      - '.github/workflows/terraform.yaml'

jobs:
  terraform:
    name: Terraform Plan/Apply
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./02-infra

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.11.4

      - name: Create YC auth key file
        run: |
          cat <<EOF > ~/.yc_authorized_key.json
          ${{ secrets.YC_SERVICE_ACCOUNT_KEY }}
          EOF
          chmod 600 ~/.yc_authorized_key.json

      - name: Create TF vars file
        run: |
          cat <<EOF > main.auto.tfvars
          ${{ secrets.TF_VARS }}
          EOF

      - name: Debug files
        run: |
          ls -la
          cat ~/.yc_authorized_key.json
          cat main.auto.tfvars

      # - name: Configure YC CLI
      #   run: |
      #     curl -sSL https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash -s -- -i /usr/local -n
      #     echo "${{ secrets.YC_SERVICE_ACCOUNT_KEY }}" | yc config set service-account-key -
      #     yc config set cloud-id ${{ secrets.YC_CLOUD_ID }}
      #     yc config set folder-id ${{ secrets.YC_FOLDER_ID }}

      - name: Extract bucket name
        id: extract_bucket
        run: |
          BUCKET_NAME=$(echo "${{ secrets.TF_VARS }}" | grep 'bucket_name' | awk -F'"' '{print $2}')
          echo "bucket_name=${BUCKET_NAME}" >> $GITHUB_OUTPUT

      - name: Terraform Init
        env:
          YC_SERVICE_ACCOUNT_KEY_FILE: ~/.yc_authorized_key.json
        run: |
          terraform init -reconfigure \
            -backend-config="bucket=${{ steps.extract_bucket.outputs.bucket_name }}" \
            -backend-config="access_key=${{ secrets.YC_S3_ACCESS_KEY }}" \
            -backend-config="secret_key=${{ secrets.YC_S3_SECRET_KEY }}"
            
      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -var-file=main.auto.tfvars

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve -var-file=main.auto.tfvars
