name: Terraform Infrastructure
on:
  push:
    branches: [ "main" ]
    paths:
      - '02-infra/**'
      - '.github/workflows/terraform.yaml'

jobs:
  terraform:
    name: Terraform Plan/Apply
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./02-infra

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.11.4

      - name: Prepare YC credentials
        run: |
          echo "${{ secrets.YC_SERVICE_ACCOUNT_KEY }}" > ~/.yc_authorized_key.json
          echo "${{ secrets.TF_VARS }}" > main.auto.tfvars
          chmod 600 ~/.yc_authorized_key.json

      - name: Debug files
        run: |
          ls -la
          cat ~/.yc_authorized_key.json
          cat main.auto.tfvars

      # - name: Configure YC CLI
      #   run: |
      #     curl -sSL https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash -s -- -i /usr/local -n
      #     echo "${{ secrets.YC_SERVICE_ACCOUNT_KEY }}" | yc config set service-account-key -
      #     yc config set cloud-id ${{ secrets.YC_CLOUD_ID }}
      #     yc config set folder-id ${{ secrets.YC_FOLDER_ID }}

      - name: Terraform Init
        env:
          YC_SERVICE_ACCOUNT_KEY_FILE: ~/.yc_authorized_key.json
        run: |
          terraform init

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -var-file=main.auto.tfvars

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve -var-file=main.auto.tfvars
